<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS3gR694\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS3gR694/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS3gR694.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS3gR694\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerS3gR694\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'S3gR694',
    'container.build_id' => 'ff1f873c',
    'container.build_time' => 1588137986,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS3gR694');
